"""
Investigations API Router.
"""
from fastapi import APIRouter, Depends, BackgroundTasks, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
from io import BytesIO

from app.database.session import get_db
from app.dependencies import get_current_user
from app.schemas.investigation import (
    InvestigationCreate,
    InvestigationResponse,
    InvestigationStatusResponse,
)
from app.schemas.finding import FindingResponse
from app.schemas.responses import APIResponse

from app.services.orchestrator.investigation_orchestrator import InvestigationOrchestrator
from app.repositories.investigation_repository import InvestigationRepository
from app.repositories.finding_repository import FindingRepository

router = APIRouter()

@router.post("/start", response_model=APIResponse[InvestigationResponse], summary="Start a new security investigation")
async def start_investigation(
    request: InvestigationCreate,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Submits a target website for security scanning and analysis.
    The process runs in the background. Check status using GET /investigations/{id}/status.
    """
    target = request.target.strip()
    if not target.startswith(("http://", "https://")):
        target = "https://" + target

    orchestrator = InvestigationOrchestrator(db)
    
    try:
        # Create investigation in pending state
        investigation = await orchestrator.create_investigation(
            target=target,
            tests=request.tests,
            mode=request.mode or "safe",
            include_ti=request.include_ti if request.include_ti is not None else True,
            tm_mode=request.tm_mode or "enhanced"
        )
        
        # Dispatch background task to execute the full pipeline
        background_tasks.add_task(
            orchestrator.run_investigation_pipeline,
            investigation.id,
            request.tests,
            request.mode or "safe"
        )
        
        # Reload with relationships
        repo = InvestigationRepository(db)
        detailed = await repo.get_by_id(investigation.id)
        
        return APIResponse(
            success=True,
            message="Investigation started successfully.",
            data=InvestigationResponse.model_validate(detailed)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to start investigation: {str(e)}"
        )


@router.get("/{id}", response_model=APIResponse[InvestigationResponse], summary="Get full investigation details")
async def get_investigation(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Fetch complete details, including findings and reports, for an investigation."""
    repo = InvestigationRepository(db)
    investigation = await repo.get_by_id(id)
    if not investigation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Investigation not found."
        )
        
    return APIResponse(
        success=True,
        data=InvestigationResponse.model_validate(investigation)
    )


@router.get("/{id}/status", response_model=APIResponse[InvestigationStatusResponse], summary="Get investigation status")
async def get_investigation_status(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Check only the current execution state and risk score for an investigation."""
    repo = InvestigationRepository(db)
    investigation = await repo.get_by_id(id)
    if not investigation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Investigation not found."
        )
        
    return APIResponse(
        success=True,
        data=InvestigationStatusResponse.model_validate(investigation)
    )


@router.get("/{id}/findings", response_model=APIResponse[List[FindingResponse]], summary="Get investigation findings")
async def get_investigation_findings(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """List all normalized findings generated by this investigation."""
    repo = FindingRepository(db)
    findings = await repo.get_by_investigation(id)
    
    validated = [FindingResponse.model_validate(f) for f in findings]
    return APIResponse(
        success=True,
        data=validated
    )


@router.get("/{id}/results", response_model=APIResponse[InvestigationResponse], summary="Get final investigation results")
async def get_investigation_results(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Fetch complete details of a finished investigation. Returns 409 if not completed yet."""
    repo = InvestigationRepository(db)
    investigation = await repo.get_by_id(id)
    if not investigation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Investigation not found."
        )
        
    if investigation.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Investigation results are not ready yet. Current status: {investigation.status}"
        )
        
    return APIResponse(
        success=True,
        data=InvestigationResponse.model_validate(investigation)
    )


# ─── Export Endpoints ─────────────────────────────────────────────


@router.get("/{id}/export/json", summary="Export investigation report as JSON")
async def export_investigation_json(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Export a completed investigation as a structured JSON file.
    Returns a downloadable JSON file containing all pipeline outputs.
    """
    repo = InvestigationRepository(db)
    investigation = await repo.get_by_id(id)
    if not investigation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Investigation not found."
        )

    if investigation.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Investigation is not completed yet. Current status: {investigation.status}"
        )

    try:
        from app.services.investigation.report_exporter import ReportExporter

        exporter = ReportExporter()
        investigation_data = {
            "target": investigation.target,
            "status": investigation.status,
            "risk_score": investigation.risk_score,
            "started_at": investigation.started_at,
            "completed_at": investigation.completed_at,
            "scan_id": investigation.scan_id,
            "findings": investigation.findings,
            "assets": investigation.assets,
            "final_result": investigation.final_result,
            "pipeline_state": investigation.pipeline_state,
        }

        result = await exporter.export_json(id, investigation_data)

        return StreamingResponse(
            BytesIO(result["content"]),
            media_type=result["mime_type"],
            headers={
                "Content-Disposition": f'attachment; filename="{result["filename"]}"',
                "Content-Length": str(result["size_bytes"]),
            },
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to export JSON: {str(e)}"
        )


@router.get("/{id}/export/pdf", summary="Export investigation report as PDF")
async def export_investigation_pdf(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Export a completed investigation as a professional PDF report.
    Includes metadata, risk score, findings, correlated threats,
    STRIDE matrix, AI summaries, and recommendations.
    """
    repo = InvestigationRepository(db)
    investigation = await repo.get_by_id(id)
    if not investigation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Investigation not found."
        )

    if investigation.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Investigation is not completed yet. Current status: {investigation.status}"
        )

    try:
        from app.services.investigation.report_exporter import ReportExporter

        exporter = ReportExporter()
        investigation_data = {
            "target": investigation.target,
            "status": investigation.status,
            "risk_score": investigation.risk_score,
            "started_at": investigation.started_at,
            "completed_at": investigation.completed_at,
            "scan_id": investigation.scan_id,
            "findings": investigation.findings,
            "assets": investigation.assets,
            "final_result": investigation.final_result,
            "pipeline_state": investigation.pipeline_state,
        }

        result = await exporter.export_pdf(id, investigation_data)

        return StreamingResponse(
            BytesIO(result["content"]),
            media_type=result["mime_type"],
            headers={
                "Content-Disposition": f'attachment; filename="{result["filename"]}"',
                "Content-Length": str(result["size_bytes"]),
            },
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to export PDF: {str(e)}"
        )
